version: 2
updates:
  - package-ecosystem: terraform
    directory: /cloudflare
    schedule:
      interval: weekly
    reviewers:
      - thymesave/core
  - package-ecosystem: terraform
    directory: /oracle-cloud/terraform-state-bucket
    schedule:
      interval: weekly
    reviewers:
      - thymesave/core
  - package-ecosystem: terraform
    directory: /oracle-cloud/network
    schedule:
      interval: weekly
    reviewers:
      - thymesave/core
