fail_fast: true
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: fix-byte-order-marker

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
        args: ['--args=--exclude=']
