couchdb_version: "latest"
couchdb_install_dir: "/opt/couchdb"
couchdb_user: couchdb
couchdb_group: couchdb
couchdb_admin_username: admin
couchdb_admin_password: s3cr3t
couchdb_admin_password_hashed: ""
couchdb_secret: ""
couchdb_cluster_uuid: ""
couchdb_cluster_nodes: []
couchdb_log_level: "info"
