---
- name: restart couchdb
  shell: docker-compose up --force-recreate -d # noqa 305 docker-compose module does not work without compose installed via pip
  args:
    chdir: "{{ couchdb_install_dir }}"
