---
- name: Base setup for all nodes
  hosts: all
  pre_tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
      become: true
    - name: Install Python 3.9
      ansible.builtin.yum:
        name: python39,python39-setuptools,python39-pip
        state: present
      become: true
      tags:
        - python
    - name: Set Python 3.9 as default
      community.general.alternatives:
        name: python3
        path: /usr/bin/python3.9
      become: true
      tags:
        - python
    - name: Install yum-utils
      ansible.builtin.yum:
        name: yum-utils
        state: present
      become: true

  roles:
    - role: geerlingguy.docker
      docker_install_compose: true
      docker_edition: 'ce'
      docker_service_state: started
      docker_service_enabled: true
      docker_daemon_options:
        log-opts:
          max-size: "50m"
      become: yes
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
          state: latest
      become: yes
