---
- name: Setup nodes
  hosts: all
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
      become: true
    - name: Install Python 3.9
      ansible.builtin.yum:
        name: python39
        state: present
      become: true
    - name: Set Python 3.9 as default
      community.general.alternatives:
        name: python3
        path: /usr/bin/python3.9
      become: true
